spring:
  datasource:
    url: jdbc:mysql://103.174.102.136:3306/xworkz_netzwerk
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xworkz_netzwerk
    password: Temp@odc
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false